remote_theme: "mmistakes/so-simple-theme@3.2.0"
skin: "/assets/css/skins/dark.css"
locale: zh-TW

title: "Shine 小光"
logo: "https://avatars.githubusercontent.com/u/100602948?v=4"
description: "你們的光也應當照耀在人前，使他們看見你們的美好工作，就榮耀你們在天上的父。 馬太福音 5:16"

read_time: true
words_per_minute: 200

# Site Author
author:
  name: "Shine 小光"
  location: "美國 德克薩斯州"
  picture: "https://avatars.githubusercontent.com/u/100602948"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github-square"
      url: https://github.com/75033us

# Footer Links
footer_links:
  - title: GitHub
    url: https://github.com/75033us
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square

copyright: 2024 Shine 小光

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-feed

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

markdown: kramdown

feed:
  path: atom.xml

# Page index
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: true

# Taxonomy
tag_archive_path: "/tags/#"

# Front Matter Defaults
defaults:
  defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: false
      share: false

